package com.linkedin.davinci.kafka.consumer;

import com.linkedin.davinci.schema.merge.MergeRecordHelper;
import com.linkedin.davinci.schema.merge.ValueAndRmd;
import com.linkedin.davinci.schema.writecompute.WriteComputeProcessor;
import com.linkedin.davinci.schema.writecompute.WriteComputeSchemaValidator;
import com.linkedin.davinci.schema.writecompute.WriteComputeSeedRmd;
import com.linkedin.davinci.serializer.avro.MapOrderPreservingSerDeFactory;
import com.linkedin.venice.exceptions.VeniceException;
import com.linkedin.venice.meta.ReadOnlySchemaRepository;
import com.linkedin.venice.serializer.AvroSerializer;
import com.linkedin.venice.serializer.FastSerializerDeserializerFactory;
import com.linkedin.venice.serializer.RecordDeserializer;
import com.linkedin.venice.serializer.RecordSerializer;
import com.linkedin.venice.utils.SparseConcurrentList;
import com.linkedin.venice.utils.collections.BiIntKeyCache;
import com.linkedin.venice.utils.lazy.Lazy;
import java.nio.ByteBuffer;
import java.util.concurrent.atomic.AtomicInteger;
import javax.annotation.Nonnull;
import org.apache.avro.Schema;
import org.apache.avro.generic.GenericRecord;
import org.apache.commons.lang.Validate;


/**
 * This class handles Write Compute operations related to a specific store.
 */
public class StoreWriteComputeProcessor {
  private final String storeName;
  private final ReadOnlySchemaRepository schemaRepo;
  private final WriteComputeProcessor writeComputeProcessor;

  /** List of serializers keyed by their value schema ID. */
  private final SparseConcurrentList<RecordSerializer<GenericRecord>> serializerIndexedBySchemaId;

  /** List of write compute schemas keyed by the unique ID generated by {@link #uniqueIdGenerator}. */
  private final SparseConcurrentList<Schema> writeComputeSchemasIndexedByUniqueId;

  /** This is a purely synthetic ID, generated by the process, and not related to any ID registered in any repository */
  private final AtomicInteger uniqueIdGenerator;

  /**
   * A read-through cache keyed by the composition of {valueSchemaId, writeComputeSchemaId}, returning a
   * {@link SchemaAndUniqueId} object. The unique ID serves as keys in {@link #writeComputeDeserializerCache}.
   */
  private final BiIntKeyCache<SchemaAndUniqueId> schemaAndUniqueIdCache;

  /**
   * A read-through cache keyed by a pair of unique IDs corresponding to the writer and reader WC schemas,
   * returning a deserializer capable of decoding from writer to reader.
   */
  private final BiIntKeyCache<RecordDeserializer<GenericRecord>> writeComputeDeserializerCache;

  private final boolean fastAvroEnabled;

  /**
   * Helper that synthesizes per-field-ts RMD records for the flag-on VT-merge fold path. Used
   * only by {@link #applyWriteComputeV2(GenericRecord, int, int, ByteBuffer, int, int, long)}.
   * Created lazily on first V2 call so non-flag-on paths pay no allocation cost.
   */
  private volatile WriteComputeSeedRmd seedRmdHelper;

  public StoreWriteComputeProcessor(
      @Nonnull String storeName,
      @Nonnull ReadOnlySchemaRepository schemaRepo,
      MergeRecordHelper mergeRecordHelper,
      boolean fastAvroEnabled) {
    Validate.notEmpty(storeName);
    Validate.notNull(schemaRepo);
    this.storeName = storeName;
    this.schemaRepo = schemaRepo;
    this.writeComputeProcessor = new WriteComputeProcessor(mergeRecordHelper);
    this.serializerIndexedBySchemaId = new SparseConcurrentList<>();
    this.writeComputeSchemasIndexedByUniqueId = new SparseConcurrentList<>();
    this.uniqueIdGenerator = new AtomicInteger();
    this.fastAvroEnabled = fastAvroEnabled;
    this.schemaAndUniqueIdCache = new BiIntKeyCache<>((valueSchemaId, writeComputeSchemaId) -> {
      final Schema valueSchema = getValueSchema(valueSchemaId);
      final Schema writeComputeSchema = getWriteComputeSchema(valueSchemaId, writeComputeSchemaId);
      WriteComputeSchemaValidator.validate(valueSchema, writeComputeSchema);
      final int uniqueId = this.uniqueIdGenerator.getAndIncrement();
      this.writeComputeSchemasIndexedByUniqueId.set(uniqueId, writeComputeSchema);
      return new SchemaAndUniqueId(uniqueId, valueSchema);
    });
    this.writeComputeDeserializerCache = new BiIntKeyCache<>((writerSchemaUniqueId, readerSchemaUniqueId) -> {
      Schema writerSchema = this.writeComputeSchemasIndexedByUniqueId.get(writerSchemaUniqueId);
      Schema readerSchema = this.writeComputeSchemasIndexedByUniqueId.get(readerSchemaUniqueId);
      return getValueDeserializer(writerSchema, readerSchema);
    });
  }

  /**
   * Apply Update operation on the current value record.
   *
   * @param currValue value record that is currently stored on this Venice server. It is null when there
   *                  is currently no value stored on this Venice server.
   * @param writeComputeBytes serialized write-compute operation.
   * @param writerValueSchemaId ID of the writer value schema.
   * @param readerValueSchemaId ID of the reader value schema.
   * @param writerUpdateProtocolVersion Update protocol version used to serialize Update payload bytes.
   * @param readerUpdateProtocolVersion Update protocol version used to deserialize Update payload bytes.
   *
   * @return {@link WriteComputeResult} of partially updated original value.
   */
  public WriteComputeResult applyWriteCompute(
      GenericRecord currValue,
      int writerValueSchemaId,
      int readerValueSchemaId,
      ByteBuffer writeComputeBytes,
      int writerUpdateProtocolVersion,
      int readerUpdateProtocolVersion) {
    int writerSchemaUniqueId = getSchemaAndUniqueId(writerValueSchemaId, writerUpdateProtocolVersion).getUniqueId();
    SchemaAndUniqueId readerSchemaContainer = getSchemaAndUniqueId(readerValueSchemaId, readerUpdateProtocolVersion);
    RecordDeserializer<GenericRecord> deserializer =
        this.writeComputeDeserializerCache.get(writerSchemaUniqueId, readerSchemaContainer.getUniqueId());
    GenericRecord writeComputeRecord = deserializer.deserialize(writeComputeBytes);

    GenericRecord updatedValue =
        writeComputeProcessor.updateRecord(readerSchemaContainer.getValueSchema(), currValue, writeComputeRecord);

    // If write compute is enabled and the record is deleted, the updatedValue will be null.
    if (updatedValue == null) {
      return new WriteComputeResult(null, null);
    }
    return new WriteComputeResult(getValueSerializer(readerValueSchemaId).serialize(updatedValue), updatedValue);
  }

  /**
   * Apply a single Update operation via the V2 algorithm (with synthesized seed RMD), used by
   * the flag-on VT-merge fold path. Behaviorally equivalent to {@link #applyWriteCompute} on
   * SET_UNION/SET_DIFF workloads, but uses the V2 algorithm's IndexedHashMap-based
   * active-element index rather than V1's O(N×M) {@code .contains()} loop. Empirically 10-58×
   * faster on append-N-floats workloads — see
   * {@code WriteComputeArrayApplyMicrobenchmark}.
   *
   * <p>The seed RMD is synthesized per call in put-only state with {@code topLevelTs=0}; the
   * caller passes a {@code modifyTimestamp >= 1} so the V2 algorithm's
   * {@code ignoreIncomingRequest} check always returns false and the operand wins. After the
   * fold, the RMD is discarded — only the materialized value bytes are returned.
   *
   * <p>This method preserves per-chain operand-order semantics (later operands win within one
   * chain when the modifyTs sequence is monotonic) but does NOT preserve cross-DC element-level
   * DCR — that would require a persistent per-(key, field) RMD cache (see GOAL.md Phase 1+2).
   *
   * @param currValue value record currently in memory (or null for empty base)
   * @param writerValueSchemaId schema id under which {@code writeComputeBytes} was serialized
   * @param readerValueSchemaId schema id under which the result must be serialized
   * @param writeComputeBytes serialized WC operand payload
   * @param writerUpdateProtocolVersion WC protocol version used by the writer
   * @param readerUpdateProtocolVersion WC protocol version to use as reader
   * @param modifyTimestamp synthetic per-operand timestamp; callers in a fold loop must pass a
   *        strictly monotonically increasing value (e.g. {@code operandIndex + 1L}).
   */
  public WriteComputeResult applyWriteComputeV2(
      GenericRecord currValue,
      int writerValueSchemaId,
      int readerValueSchemaId,
      ByteBuffer writeComputeBytes,
      int writerUpdateProtocolVersion,
      int readerUpdateProtocolVersion,
      long modifyTimestamp) {
    int writerSchemaUniqueId = getSchemaAndUniqueId(writerValueSchemaId, writerUpdateProtocolVersion).getUniqueId();
    SchemaAndUniqueId readerSchemaContainer = getSchemaAndUniqueId(readerValueSchemaId, readerUpdateProtocolVersion);
    RecordDeserializer<GenericRecord> deserializer =
        this.writeComputeDeserializerCache.get(writerSchemaUniqueId, readerSchemaContainer.getUniqueId());
    GenericRecord writeComputeRecord = deserializer.deserialize(writeComputeBytes);

    final Schema readerValueSchema = readerSchemaContainer.getValueSchema();
    WriteComputeSeedRmd helper = getOrInitSeedRmdHelper();
    Schema rmdSchema = helper.getRmdSchema(storeName, readerValueSchemaId, readerValueSchema);
    GenericRecord seedRmd = helper.buildSeedRmd(rmdSchema, readerValueSchema);

    final GenericRecord effectiveCurrValue = currValue;
    ValueAndRmd<GenericRecord> input = new ValueAndRmd<>(Lazy.of(() -> effectiveCurrValue), seedRmd);
    ValueAndRmd<GenericRecord> output =
        writeComputeProcessor.updateRecordWithRmd(readerValueSchema, input, writeComputeRecord, modifyTimestamp, -1);

    GenericRecord updatedValue = output.getValue();
    // V2 returns the synthetic seedRmd record (now mutated). When the original currValue was
    // null and no field was updated, output.isUpdateIgnored() returns true and updatedValue is
    // a default-filled record. Mirror applyWriteCompute's contract: null updatedValue means
    // "WC delete tombstone" — but V2 path never produces a true delete, so we always serialize.
    if (updatedValue == null) {
      return new WriteComputeResult(null, null);
    }
    return new WriteComputeResult(getValueSerializer(readerValueSchemaId).serialize(updatedValue), updatedValue);
  }

  /**
   * Variant of {@link #applyWriteComputeV2} that accepts an existing {@link ValueAndRmd} container
   * so the caller can persist RMD state across multiple operand applications within one fold call.
   *
   * <p>Used by the VT-merge fold path: the chain may contain multiple operands targeting the same
   * collection field. The V2 algorithm uses {@code CollectionRmdTimestamp.isInPutOnlyState()} (and
   * the per-element-ts arrays) to decide element-level DCR for each operand. If the RMD is rebuilt
   * fresh for each operand (the simple {@link #applyWriteComputeV2} overload), operand N+1 doesn't
   * see operand N's RMD mutations — so element-level DCR fails across the chain.
   *
   * <p>This overload mutates the supplied {@code valueAndRmd} in place: after the call,
   * {@code valueAndRmd.getValue()} is the updated value record and {@code valueAndRmd.getRmd()}
   * reflects the cumulative RMD state from all applied operands.
   *
   * @param valueAndRmd  pre-built input; caller owns construction (typically seeded from the base
   *                     record at fold start)
   * @param writerValueSchemaId schema id under which {@code writeComputeBytes} was serialized
   * @param readerValueSchemaId schema id under which the result must be deserialized
   * @param writeComputeBytes the WC operand payload
   * @param writerUpdateProtocolVersion WC protocol version used by the writer
   * @param readerUpdateProtocolVersion WC protocol version to use as reader
   * @param modifyTimestamp the operand's logical timestamp (for DCR)
   */
  public WriteComputeResult applyWriteComputeV2WithExternalRmd(
      ValueAndRmd<GenericRecord> valueAndRmd,
      int writerValueSchemaId,
      int readerValueSchemaId,
      ByteBuffer writeComputeBytes,
      int writerUpdateProtocolVersion,
      int readerUpdateProtocolVersion,
      long modifyTimestamp) {
    int writerSchemaUniqueId = getSchemaAndUniqueId(writerValueSchemaId, writerUpdateProtocolVersion).getUniqueId();
    SchemaAndUniqueId readerSchemaContainer = getSchemaAndUniqueId(readerValueSchemaId, readerUpdateProtocolVersion);
    RecordDeserializer<GenericRecord> deserializer =
        this.writeComputeDeserializerCache.get(writerSchemaUniqueId, readerSchemaContainer.getUniqueId());
    GenericRecord writeComputeRecord = deserializer.deserialize(writeComputeBytes);

    final Schema readerValueSchema = readerSchemaContainer.getValueSchema();
    ValueAndRmd<GenericRecord> output = writeComputeProcessor
        .updateRecordWithRmd(readerValueSchema, valueAndRmd, writeComputeRecord, modifyTimestamp, -1);

    GenericRecord updatedValue = output.getValue();
    if (updatedValue == null) {
      return new WriteComputeResult(null, null);
    }
    return new WriteComputeResult(getValueSerializer(readerValueSchemaId).serialize(updatedValue), updatedValue);
  }

  /** Returns the value schema for {@code readerValueSchemaId}, used by fold-path seed builders. */
  public Schema getReaderValueSchema(int readerValueSchemaId) {
    return getValueSchema(readerValueSchemaId);
  }

  /** Returns the RMD schema for {@code readerValueSchemaId}, used by fold-path seed builders. */
  public Schema getReaderRmdSchema(int readerValueSchemaId) {
    Schema valueSchema = getValueSchema(readerValueSchemaId);
    WriteComputeSeedRmd helper = getOrInitSeedRmdHelper();
    return helper.getRmdSchema(storeName, readerValueSchemaId, valueSchema);
  }

  /** Serialize a value record under the given schemaId. Used by the fold path. */
  public byte[] serializeValueRecord(int valueSchemaId, GenericRecord record) {
    return getValueSerializer(valueSchemaId).serialize(record);
  }

  /**
   * Build a seed RMD record for the fold path. Convenience for callers that don't want to manage
   * the {@link WriteComputeSeedRmd} helper directly. Caller may post-process the returned record
   * (e.g. to honor §4.2/§4.3 gotchas based on the base value record).
   */
  public GenericRecord buildSeedRmd(int readerValueSchemaId) {
    Schema valueSchema = getValueSchema(readerValueSchemaId);
    WriteComputeSeedRmd helper = getOrInitSeedRmdHelper();
    Schema rmdSchema = helper.getRmdSchema(storeName, readerValueSchemaId, valueSchema);
    return helper.buildSeedRmd(rmdSchema, valueSchema);
  }

  private WriteComputeSeedRmd getOrInitSeedRmdHelper() {
    WriteComputeSeedRmd local = seedRmdHelper;
    if (local == null) {
      synchronized (this) {
        local = seedRmdHelper;
        if (local == null) {
          local = new WriteComputeSeedRmd();
          seedRmdHelper = local;
        }
      }
    }
    return local;
  }

  private SchemaAndUniqueId getSchemaAndUniqueId(int valueSchemaId, int writeComputeSchemaId) {
    return schemaAndUniqueIdCache.get(valueSchemaId, writeComputeSchemaId);
  }

  RecordDeserializer<GenericRecord> getValueDeserializer(Schema writerSchema, Schema readerSchema) {
    if (fastAvroEnabled) {
      return FastSerializerDeserializerFactory.getFastAvroGenericDeserializer(writerSchema, readerSchema);
    }

    /**
     * It is not necessary to preserve the map-order since this class is only used by {@link LeaderFollowerStoreIngestionTask}.
     * We are not supposed to run DCR validation workflow against non-AA store.
     */
    // Map in write compute needs to have consistent ordering. On the sender side, users may not care about ordering
    // in their maps. However, on the receiver side, we still want to make sure that the same serialized map bytes
    // always get deserialized into maps with the same entry ordering.
    return MapOrderPreservingSerDeFactory.getDeserializer(writerSchema, readerSchema);
  }

  private RecordSerializer<GenericRecord> getValueSerializer(int valueSchemaId) {
    return serializerIndexedBySchemaId.computeIfAbsent(valueSchemaId, this::generateValueSerializer);
  }

  RecordSerializer<GenericRecord> generateValueSerializer(int valueSchemaId) {
    Schema valueSchema = getValueSchema(valueSchemaId);
    /**
     * It is not necessary to preserve the map-order since this class is only used by {@link LeaderFollowerStoreIngestionTask}.
     * We are not supposed to run DCR validation workflow against non-AA store.
     */
    if (fastAvroEnabled) {
      return FastSerializerDeserializerFactory.getFastAvroGenericSerializer(valueSchema);
    }
    return new AvroSerializer<>(valueSchema);
  }

  private Schema getValueSchema(int valueSchemaId) {
    Schema valueSchema = schemaRepo.getValueSchema(storeName, valueSchemaId).getSchema();
    if (valueSchema == null) {
      throw new VeniceException(
          String.format("Cannot find value schema for store: %s, value schema id: %d", storeName, valueSchemaId));
    }
    return valueSchema;
  }

  private Schema getWriteComputeSchema(int valueSchemaId, int writeComputeSchemaId) {
    Schema writeComputeSchema = schemaRepo.getDerivedSchema(storeName, valueSchemaId, writeComputeSchemaId).getSchema();
    if (writeComputeSchema == null) {
      throw new VeniceException(
          String.format(
              "Cannot find write-compute schema for store: %s, value schema id: %d," + " write-compute schema id: %d",
              storeName,
              valueSchemaId,
              writeComputeSchemaId));
    }
    return writeComputeSchema;
  }

  /**
   * A POJO to encapsulate value schema and a unique ID associated with a pair of value schema and write compute schema
   */
  private static class SchemaAndUniqueId {
    private final int uniqueId;
    private final Schema valueSchema;

    SchemaAndUniqueId(int uniqueId, @Nonnull Schema valueSchema) {
      this.uniqueId = uniqueId;
      this.valueSchema = valueSchema;
    }

    int getUniqueId() {
      return uniqueId;
    }

    Schema getValueSchema() {
      return valueSchema;
    }
  }
}
